"""add emergency gps coordinates

Revision ID: 7908c4504b1a
Revises: b59bfbc688ae
Create Date: 2026-08-06 17:15:34.177990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7908c4504b1a'
down_revision: Union[str, Sequence[str], None] = 'b59bfbc688ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "emergencies",
        sa.Column(
            "latitude",
            sa.Float(),
            nullable=False,
            server_default="0"
        )
    )

    op.add_column(
        "emergencies",
        sa.Column(
            "longitude",
            sa.Float(),
            nullable=False,
            server_default="0"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergencies', 'longitude')
    op.drop_column('emergencies', 'latitude')
    # ### end Alembic commands ###
