"""initial migration

Revision ID: b59bfbc688ae
Revises: 
Create Date: 2026-08-06 16:57:07.191794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59bfbc688ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ambulances',
        sa.Column(
            'latitude',
            sa.Float(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'ambulances',
        sa.Column(
            'longitude',
            sa.Float(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'hospitals',
        sa.Column(
            'latitude',
            sa.Float(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'hospitals',
        sa.Column(
            'longitude',
            sa.Float(),
            nullable=False,
            server_default='0'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'longitude')
    op.drop_column('hospitals', 'latitude')
    op.drop_column('ambulances', 'longitude')
    op.drop_column('ambulances', 'latitude')
    # ### end Alembic commands ###
